### ISSUE TITLE
Module Upgrade in Crafting Manager causing crash report

### ISSUE THREAD

**Issue by Aelrath** [tom5454/LogisticsBridge#31]
I'm trying to apply a Fluid Crafting Upgrade to a Crafting Module. Usually you would apply a Module Upgrade to the Chassis Pipe so it shows the two upgrade slots for the modules. I've seen the middle mouse button menu of a module inside the Crafting Manager  that says "Pick Upgrade from Slot 1" but I have no way of interacting with the module to apply the upgrade. If I try and use the Module Upgrade on the Crafting Manager this crash report happens.

`java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 20
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 20
    at logisticspipes.network.NewGuiHandler.openGui(NewGuiHandler.java:147)
    at logisticspipes.network.packets.gui.OpenGUIPacket.processPacket(OpenGUIPacket.java:53)
    at logisticspipes.network.PacketInboundHandler.inThreadProcessPacket(PacketInboundHandler.java:35)
    at logisticspipes.network.PacketInboundHandler.lambda$channelRead0$0(PacketInboundHandler.java:29)
    at logisticspipes.network.PacketInboundHandler$$Lambda$5821/1599523183.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20
    at logisticspipes.gui.GuiChassiPipe.<init>(GuiChassiPipe.java:66)
    at logisticspipes.network.guis.pipe.ChassiGuiProvider.getClientGui(ChassiGuiProvider.java:33)
    at logisticspipes.network.NewGuiHandler.openGui(NewGuiHandler.java:141)
    ... 16 more
`

**Comment by tom5454** [comment]
You don't need a module upgrade in the crafting manager. You can install upgrades by dropping the upgrade on the module slot, and pick it up with the middle click menu.

**Comment by Aelrath** [comment]
Thank you that worked perfectly.

**Comment by tom5454** [comment]
I'm working on an update, I added it to the tooltip.
