### ISSUE TITLE
Placing AE bridge breaks the server

### ISSUE THREAD

**Issue by ArmaWizard** [tom5454/LogisticsBridge#35]
I have a medium big logistics pipes system, but when I use the bridge pipe + AE bridge the server almost comes to halt.
It drops to around 5TPS, when i remove the bridge it instantly catches back up.

Placing AE bridge
![image](https://user-images.githubusercontent.com/6765262/89200430-4d88e900-d5b0-11ea-9b04-fedb629e4712.png)

Removing AE bridge
![image](https://user-images.githubusercontent.com/6765262/89200539-76a97980-d5b0-11ea-848c-b61ed8174644.png)

**Comment by ArmaWizard** [comment]
Note this is on 1.3.9 version. And latest stable logistics pipes version + appliedenergistics2-rv6-stable-7

**Comment by tom5454** [comment]
I optimized the bridging logic and added a profiler, please right click the AE bridge with a stick to see which part creates lag and send the report here.

**Comment by ArmaWizard** [comment]
Will do

**Comment by ArmaWizard** [comment]
Alright I just updated; but on server start:


---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2020-08-19 14:30:47 CEST
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.tom.logisticsbridge.LogisticsBridge.registerPipe(LogisticsBridge.java:190)
    at com.tom.logisticsbridge.LogisticsBridge.initItems(LogisticsBridge.java:164)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2407_LogisticsBridge_initItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1259)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:1206)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.tom.logisticsbridge.LogisticsBridge.registerPipe(LogisticsBridge.java:188)
    ... 13 more
Caused by: java.lang.NoSuchFieldError: clientInv
    at com.tom.logisticsbridge.pipe.CraftingManager.<init>(CraftingManager.java:73)
    at logisticspipes.pipes.basic.LogisticsBlockGenericPipe.createPipe(LogisticsBlockGenericPipe.java:197)
    at logisticspipes.pipes.basic.LogisticsBlockGenericPipe.registerPipe(LogisticsBlockGenericPipe.java:183)
    at logisticspipes.LogisticsPipes.registerPipe(LogisticsPipes.java:682)
    ... 18 more

Would you recommend placing the old version back in, removing the pipes, updating, adding the pipes again?

**Comment by ArmaWizard** [comment]
Alright, did the above. Remove, update, add. Still crash on startup.

**Comment by tom5454** [comment]
Fixed the crash on startup.

**Comment by ArmaWizard** [comment]
Alright I will update and post the profiler output again.

**Comment by dominic-jones** [comment]
I too encountered a similar sounding issue. I connected a trivial AE system to a large (routing table size 1339) LP system. Immediately started getting slow and skipped ticks.

Again on Logistics Bridge 1.13.11 in the FTBInteractions modpack.

Did you say this was fixed in later versions, or are you still gathering data?

I ran the diagnostic also - 
![image](https://user-images.githubusercontent.com/5888934/91778975-b2e9ed00-ebe3-11ea-8d55-c83041d1f736.png)

**Comment by dominic-jones** [comment]
Upgrading to use 1.3.13 seems to alleviate the symptoms of slow server ticking when simply connecting the networks. I cannot get AE2 to request from LP, but that's another issue :)

**Comment by desagas** [comment]
I can confirm this in 2.0.9 Interactions, placing the bridge with the pipe connected caused 2 things to happen:

1. About every 20 seconds or so, the bridge would spike tps, and would cause a major drop in performance.

2. When requesting a crafting recipe through my request table, while having the bridge pipe and block connected to AE2 crafting grid and energy provider only, set to default and smart, the system instantly died. TPS dropped to 3, the bridge block was up to 9,100 ns/t, and the pridge pipe was at 50,000ns/t, and the crafting manager that was supposed to receive the items which were all available before connecting the bridge, shot up to 101,000ns/t. This never happened without the bridge connected. It seems as though this is a one way bridge only, crafting with AE2, and delivering with LP, but not the other way around.

**Comment by zanetano** [comment]
I have the same issue. (tps drops to 5  /  tick time: 200ms and climbing until crash.)
I'm playing FTB Interactions 2.0.9 which has: 
-Logi Bridge:1.3.11
-Logi Pipes:0.10.3.62
-AE:rv6-stable-7

![image](https://user-images.githubusercontent.com/54339342/108762135-a1a4ec00-7547-11eb-8b15-5a44568f4441.png)
