### ISSUE TITLE
crash after placing ae bridge and ae bridge pipe

### ISSUE THREAD

**Issue by mightydanp** [tom5454/LogisticsBridge#49]
i am on ftb interactions and after placing the two blocks down to join logistics pipes and ae2 systems gave severe server lag and after a few minutes the server crashed

`java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
    at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:673)
    at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1217)
    at net.minecraft.item.ItemStack.<init>(ItemStack.java:112)
    at net.minecraft.item.ItemStack.<init>(ItemStack.java:98)
    at net.minecraft.item.ItemStack.<init>(ItemStack.java:95)
    at com.tom.logisticsbridge.LogisticsBridge.fakeStack(LogisticsBridge.java:336)
    at com.tom.logisticsbridge.tileentity.TileEntityBridgeAE.lambda$getAvailableItems$9(TileEntityBridgeAE.java:398)
    at com.tom.logisticsbridge.tileentity.TileEntityBridgeAE$$Lambda$4844/590400180.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.tom.logisticsbridge.tileentity.TileEntityBridgeAE.getAvailableItems(TileEntityBridgeAE.java:400)
    at appeng.me.storage.NetworkInventoryHandler.getAvailableItems(NetworkInventoryHandler.java:255)
    at appeng.me.cache.NetworkMonitor.getAvailableItems(NetworkMonitor.java:117)
    at com.tom.logisticsbridge.tileentity.TileEntityBridgeAE.getItems(TileEntityBridgeAE.java:173)
    at com.tom.logisticsbridge.pipe.BridgePipe.canCraft(BridgePipe.java:473)
    at com.tom.logisticsbridge.pipe.BridgePipe.canProvide(BridgePipe.java:175)
    at logisticspipes.request.RequestTreeNode.checkProvider(RequestTreeNode.java:355)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:74)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57)
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:43)
    at logisticspipes.request.RequestTree.request(RequestTree.java:175)
    at logisticspipes.request.RequestTree.requestPartial(RequestTree.java:204)
    at logisticspipes.modules.ModuleActiveSupplier.createSupplyRequest(ModuleActiveSupplier.java:333)
    at logisticspipes.modules.ModuleActiveSupplier.lambda$tick$5(ModuleActiveSupplier.java:180)
    at logisticspipes.modules.ModuleActiveSupplier$$Lambda$4807/1392154253.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at logisticspipes.modules.ModuleActiveSupplier.tick(ModuleActiveSupplier.java:176)
    at logisticspipes.modules.ChassiModule.tick(ChassiModule.java:127)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:448)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.update(LogisticsTileGenericPipe.java:213)
    at net.minecraft.world.World.redirect$zzk000$tileEntityUpdate(World.java:4137)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)`

**Comment by mightydanp** [comment]
.11 version of this mod and appliedenergistics2-rv6-stable-7
