### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rsfuja** [tom5454/LogisticsBridge#6]
Crash directly after attaching bridge pipe to logistics pipe system.

> ---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2019-10-01 22:07:31 EDT
Description: Ticking block entity

java.lang.NullPointerException
    at com.tom.logisticsbridge.pipe.BridgePipe.canCraft(BridgePipe.java:386)
    at com.tom.logisticsbridge.pipe.BridgePipe.canProvide(BridgePipe.java:90)
    at logisticspipes.request.RequestTreeNode.checkProvider(RequestTreeNode.java:355)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:74)
    at logisticspipes.request.RequestTreeNode.<init>(RequestTreeNode.java:57)
    at logisticspipes.request.RequestTree.<init>(RequestTree.java:43)
    at logisticspipes.request.RequestTree.requestFluid(RequestTree.java:221)
    at logisticspipes.request.RequestTree.requestFluidPartial(RequestTree.java:212)
    at logisticspipes.pipes.PipeFluidSupplierMk2.lambda$throttledUpdateEntity$6(PipeFluidSupplierMk2.java:182)
    at logisticspipes.pipes.PipeFluidSupplierMk2$$Lambda$6130/1798582400.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at logisticspipes.pipes.PipeFluidSupplierMk2.throttledUpdateEntity(PipeFluidSupplierMk2.java:116)
    at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:398)
    at logisticspipes.pipes.basic.LogisticsTileGenericPipe.update(LogisticsTileGenericPipe.java:213)
    at net.minecraft.world.World.redirect$tileEntityUpdate$zbm000(World.java:5132)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: logisticspipes:pipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
  Block type: ID #2849 (tile.logisticspipes.pipe // logisticspipes.pipes.basic.LogisticsBlockGenericPipe // logisticspipes:pipe)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-10,92,23), Chunk: (at 6,5,7 in -1,1; contains blocks -16,0,16 to -1,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Actual block type: ID #2849 (tile.logisticspipes.pipe // logisticspipes.pipes.basic.LogisticsBlockGenericPipe // logisticspipes:pipe)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {turtleConnect_3:0b,turtleConnect_4:0b,turtleConnect_1:0b,"tank[4]":{Empty:""},turtleConnect_2:0b,"tank[2]":{Empty:""},turtleConnect_5:0b,"tank[0]":{Empty:""},stat_lifetime_recieved:1681L,turtleConnect_6:0b,buffercontents:[],stat_lifetime_sent:0L,travelingEntities:[],logicController:{LogicDiskInvitems:[],LogicDiskInvitemsCount:1},itemsCount:1,routerId:"010dfab6-16e5-4afa-9685-89136b07c4a2",PipeSign_4:0b,ForgeCaps:{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}},upgradeManager:{UpgradeInventory_items:[],SecurityInventory_items:[],SneakyUpgradeInventory_items:[],UpgradeInventory_itemsCount:9,SneakyUpgradeInventory_itemsCount:9,SecurityInventory_itemsCount:1},PipeSign_5:0b,id:"logisticspipes:pipe",sendqueue:[],"tank[5]":{Empty:""},"tank[3]":{Empty:""},amount:18000,"tank[1]":{Empty:""},PipeSign_0:0b,PipeSign_1:0b,PipeSign_2:0b,PipeSign_3:0b,"tank[middle]":{Empty:""},requestpartials:1b,pipeId:8389,stat_lifetime_relayed:3637L,x:-10,y:92,z:23,_bucketMinimum:1b,items:[{index:0,id:"logisticspipes:fluid_container",Count:1b,tag:{FluidName:"aluminum",Amount:1},Damage:0s}],turtleConnect_0:0b}
  LP-Version: 0.10.2.208:false
  Pipe: logisticspipes.pipes.PipeFluidSupplierMk2
  Transport: logisticspipes.transport.PipeFluidTransportLogistics
  Router: ServerRouter: {ID: 27, UUID: 010dfab6-16e5-4afa-9685-89136b07c4a2, AT: (0, -10, 92, 23), Version: 116), Destroyed: false}
  stillNeedReplace: false

-- Affected level --
  Level name: Deeper Skart
  All players: 1 total; [EntityPlayerMP['KidVoodoo'/35597342, l='Deeper Skart', x=-8.11, y=81.16, z=-4.77]]
  Chunk stats: ServerChunkCache: 478 Drop: 0
  Level seed: 3999754382332305788
  Level generator: ID 11 - voidworld, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (0,90,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 1683594 game time, 1683594 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 74255 (now: false), thunder time: 22424 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1564921584 bytes (1492 MB) / 6360137728 bytes (6065 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 286 mods loaded, 286 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by rsfuja** [comment]
Works great now, thanks!
